import 'package:flutter/material.dart';

import 'package:standard_searchbar/standard_searchbar.dart';

void main() => runApp(const MyApp());

const suggestions = [
  'apple',
  'banana',
  'chocolate',
  'dog',
  'elephant',
  'forest',
  'guitar',
  'house',
  'igloo',
  'jazz',
  'kangaroo',
  'lemon',
  'mango',
  'napkin',
  'ocean',
  'piano',
  'quilt',
  'rainbow',
  'sunset',
  'tiger',
  'umbrella',
  'violin',
  'whale',
  'xylophone',
  'yogurt',
  'zebra',
  'anchor',
  'bird',
  'cat',
  'dragon',
  'eagle',
  'flamingo',
  'giraffe',
  'horse',
  'iguana',
  'jellyfish',
  'koala',
  'lion',
  'monkey',
  'narwhal',
  'octopus',
  'panda',
  'quokka',
  'raccoon',
  'snail',
  'toucan',
  'unicorn',
  'vulture',
  'wolf',
  'yak',
  'zeppelin',
  'sapphire',
  'moonlight',
  'whisper',
  'cascade',
  'serendipity',
  'effervescent',
  'triumphant',
  'labyrinth',
  'ethereal',
  'enchanting',
  'mellifluous',
  'butterfly',
  'soothing',
  'verdant',
  'eloquent',
  'blossom',
  'tranquil',
  'harmony',
  'quintessence',
  'silhouette',
  'ephemeral',
  'whimsical',
  'resplendent',
  'petrichor',
  'nostalgia',
  'gossamer',
  'velvet',
  'aurora',
  'evanescent',
  'luminescent',
  'scintilla',
  'lullaby',
  'ephemera',
  'sonorous',
  'surreptitious',
  'incandescent',
  'murmur',
  'solitude',
  'veranda',
  'lilac',
  'crepuscular',
  'umbra',
  'dalliance',
  'cascading',
  'halcyon',
  'wisteria',
  'cherish',
  'twilight',
  'ephemeron',
  'enigma',
  'effulgent',
  'serene',
  'whimsy',
  'cascade',
  'insouciant',
  'oblivion',
  'ephemeral',
  'iridescent',
  'languor',
  'mellifluous',
  'petrichor',
  'quixotic',
  'scintilla',
  'sonorous',
  'resplendent',
  'tranquil',
  'euphoria',
  'gossamer',
  'labyrinth',
  'nirvana',
  'velvet',
  'zephyr',
  'halcyon',
  'serendipity',
  'luminous',
  'effervescent',
  'solitude',
  'melancholy',
  'azure',
  'ephemeron',
  'quintessence',
  'evanescent',
  'nostalgia',
  'crepuscular',
  'tranquility',
  'ethereal',
  'sculpture',
  'harmony',
  'whisper',
  'glisten',
  'placid',
  'lullaby',
  'incandescent',
  'soothe',
  'bucolic',
  'surreptitious',
  'lilting',
  'effulgence',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
];

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Standard SearchBar Example'),
        ),
        body: const SizedBox(
          width: double.infinity,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              SizedBox(height: 50),
              StandardSearchBar(
                width: 360,
                suggestions: [
                  'apple',
                  'banana',
                  'melon',
                  'orange',
                  'pineapple',
                  'strawberry',
                ],
              ),
              SizedBox(height: 200),
            ],
          ),
        ),
        // backgroundColor: Colors.black12,
        backgroundColor: const Color(0xFF12202F),
      ),
    );
  }
}
